#ifndef DETECTION_DUMMY_H_
#define DETECTION_DUMMY_H_


#include "../../inc/radar_common.h"

#define DUMMY_RDM_RANGE_BINS		2048
#define DUMMY_RDM_DOPPLER_BINS		32
#define DUMMY_FRAME_NUM_1			1
#define DUMMY_FRAME_NUM_10			10
#define DUMMY_FRAME_NUM_33			33
#define DUMMY_FRAME_NUM_REAL		DUMMY_FRAME_NUM_33
#define DUMMY_FRAME_NUM_1_SIZE		(DUMMY_RDM_RANGE_BINS * DUMMY_RDM_DOPPLER_BINS * DUMMY_FRAME_NUM_1)
#define DUMMY_FRAME_NUM_10_SIZE		(DUMMY_RDM_RANGE_BINS * DUMMY_RDM_DOPPLER_BINS * DUMMY_FRAME_NUM_10)
#define DUMMY_FRAME_NUM_33_SIZE		(DUMMY_RDM_RANGE_BINS * DUMMY_RDM_DOPPLER_BINS * DUMMY_FRAME_NUM_33)

extern uint32_t rdmDummyData_1target[DUMMY_FRAME_NUM_1_SIZE];
extern uint32_t rdmDummyData_20target[DUMMY_FRAME_NUM_1_SIZE];
extern uint32_t rdmDummyData_3target_10frame[DUMMY_FRAME_NUM_10_SIZE];
extern uint32_t rdmDummyData_xingren_33frame[DUMMY_FRAME_NUM_33_SIZE];


#endif /*DETECTION_DUMMY_H_*/
